using Focus.Common.DataStructs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FocusSalesModule.Queries
{
    public class ProductQueries
    {
        public static string GetBrStockIn(string rmano)
        {
            return $"SELECT pr.iMasterId ItemId,pr.sCode ItemCode,pr.sName ItemName,muts.iMasterId UnitId, rma.sRmaNo RmaNo,muts.sName UnitName,1 Stock,PostedRma =(select count(hh.iHeaderId) from  tCore_Header_0 hh JOIN tCore_Data_0 dd ON hh.iHeaderId = dd.iHeaderId left join tCore_Rma_0 rrma on rrma.iBodyId = dd.iBodyId where  hh.ivouchertype= 2053 and rrma.sRmaNo = '{rmano}'),Price=(select top 1 iif(fval0=0, fval1, fval0) from mCore_SellingPriceBookDetails where iProductId = pr.iMasterId order by iStartDate desc), d.iTransactionId TxnId, l.iRefId RefId,  l.iLinkId LinkId, l.bBase Base, bClosed Closed,CONCAT(v.sAbbr,':',h.sVoucherNo) LinkVoucherNo,h.iVoucherType LinkVoucherType, h.sVoucherNo DocNo                   FROM tCore_Header_0 h\r\n                    JOIN tCore_Data_0 d ON h.iHeaderId = d.iHeaderId\r\n                    left join tCore_Rma_0 rma on rma.iBodyId = d.iBodyId\r\n                    JOIN tCore_Indta_0 s ON d.iBodyId = s.iBodyId\r\n                    JOIN mCore_Product pr ON pr.iMasterId = s.iProduct\r\n                    join tCore_Links_0 l on l.iTransactionId = d.iTransactionId\r\n                    left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit\r\n                    join cCore_Vouchers_0 v on v.iVoucherType = h.iVoucherType WHERE rma.sRmaNo = '{rmano}' and h.iVoucherType = 5380 ";
        }
        public static string GetRmaData(string rmano, int outletId)
        {
            return $"select pr.iMasterId ItemId,pr.sCode ItemCode,pr.sName ItemName,muts.iMasterId UnitId, muts.sName UnitName,Price=(select top 1 iif(fval0=0, fval1, fval0) from mCore_SellingPriceBookDetails where iProductId = pr.iMasterId order by iStartDate desc),RmaNo, Qty Stock  from (select iProduct, RmaNo, sum(Qty)  Qty from(SELECT iProduct, rma.sRmaNo RmaNo, 1 Qty FROM tCore_Header_0 JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n        AND iProductType<> 1 AND iProductType<> 5\r\n        AND iStatus<> 5 and fQuantityInBase > 0 and tCore_Data_0.iInvTag = {outletId} union all\r\nSELECT iProduct, rma.sRmaNo RmaNo, -1 ReceiptQty\r\n                    FROM tCore_Header_0\r\n                    JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId\r\n\r\n                    left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId\r\n\r\n                    JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId\r\n                    JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n                    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n                       AND iProductType<> 1 AND iProductType<> 5\r\n                     AND iStatus<> 5 and fQuantityInBase< 0 and tCore_Data_0.iInvTag = {outletId}) dt group by iProduct, RmaNo\r\n  ) dt join mcore_product pr on pr.imasterid = dt.iProduct left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit   order by iProduct";
        }
        public static string GetSalesReturnCount(string rmano)
        {
            return $"SELECT count(h.iHeaderId) FROM tCore_Header_0 h JOIN tCore_Data_0 d ON h.iHeaderId = d.iHeaderId left join tCore_Rma_0 rma on rma.iBodyId = d.iBodyId JOIN tCore_Indta_0 ind  ON d.iBodyId = ind.iBodyId join mcore_product pr on pr.imasterid = ind.iProduct left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit left join tCore_Data_Tags_0 tg on tg.iBodyId = d.iBodyId left join mPos_Member mbr on mbr.iMasterId = tg.iTag1106 WHERE rma.sRmaNo = '{rmano}'    and h.iVoucherType = 1793 ";
        }
        public static string GetSalesReturnRmaData(string rmano, int outletId, int memberId)
        {
            return $"SELECT h.sVoucherNo DocNo,pr.iMasterId ItemId,pr.sCode ItemCode,pr.sName ItemName,muts.iMasterId UnitId, muts.sName UnitName,Price=abs(ind.mRate),rma.sRmaNo RmaNo,1  Stock , mbr.imasterid MemberId,dd.VoucherCode , sd.mVal1 VoucherDiscount FROM tCore_Header_0 h JOIN tCore_Data_0 d ON h.iHeaderId = d.iHeaderId  left join tCore_Data3334_0 dd on dd.iBodyId = d.iBodyId  left join  tCore_IndtaBodyScreenData_0 sd on sd.iBodyId = d.iBodyId left join tCore_Rma_0 rma on rma.iBodyId = d.iBodyId JOIN tCore_Indta_0 ind  ON d.iBodyId = ind.iBodyId join mcore_product pr on pr.imasterid = ind.iProduct left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit left join tCore_Data_Tags_0 tg on tg.iBodyId = d.iBodyId left join mPos_Member mbr on mbr.iMasterId = tg.iTag1106 WHERE rma.sRmaNo = '{rmano}' AND bSuspended = 0  AND d.iAuthStatus < 2   and h.iVoucherType = 3334 and mbr.imasterid = {memberId} and d.iInvTag = {outletId}";
        }
        public static string GetSalesReturnRmaData(string rmano, int outletId)
        {
            return $"select pr.iMasterId ItemId,pr.sCode ItemCode,pr.sName ItemName,muts.iMasterId UnitId, muts.sName UnitName,Price=(select top 1 iif(fval0=0, fval1, fval0) from mCore_SellingPriceBookDetails where iProductId = pr.iMasterId order by iStartDate desc),RmaNo, Qty Stock  from (select iProduct, RmaNo, sum(Qty)  Qty from(SELECT iProduct, rma.sRmaNo RmaNo, 1 Qty FROM tCore_Header_0 JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n        AND iProductType<> 1 AND iProductType<> 5\r\n        AND iStatus<> 5 and fQuantityInBase > 0 and tCore_Data_0.iInvTag = {outletId} union all\r\nSELECT iProduct, rma.sRmaNo RmaNo, -1 ReceiptQty\r\n                    FROM tCore_Header_0\r\n                    JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId\r\n\r\n                    left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId\r\n\r\n                    JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId\r\n                    JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n                    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n                       AND iProductType<> 1 AND iProductType<> 5\r\n                     AND iStatus<> 5 and fQuantityInBase< 0 and tCore_Data_0.iInvTag = {outletId}) dt group by iProduct, RmaNo\r\n  ) dt join mcore_product pr on pr.imasterid = dt.iProduct left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit   order by iProduct";
        }
        public static string GetRmaDataNoOutlet(string rmano, int outletId)
        {
            return $"select uts.iDefaultSalesUnit UnitId,pr.iMasterId ItemId,pr.sCode ItemCode,pr.sName ItemName,muts.iMasterId UnitId, muts.sName UnitName,Price=(select top 1 iif(fval0=0, fval1, fval0) from mCore_SellingPriceBookDetails where iProductId = pr.iMasterId order by iStartDate desc),RmaNo, Qty Stock  from (select iProduct, RmaNo, sum(Qty)  Qty from(SELECT iProduct, rma.sRmaNo RmaNo, 1 Qty FROM tCore_Header_0 JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n        AND iProductType<> 1 AND iProductType<> 5\r\n        AND iStatus<> 5 and fQuantityInBase > 0  union all\r\nSELECT iProduct, rma.sRmaNo RmaNo, -1 ReceiptQty\r\n                    FROM tCore_Header_0\r\n                    JOIN tCore_Data_0 ON tCore_Header_0.iHeaderId = tCore_Data_0.iHeaderId\r\n\r\n                    left join tCore_Rma_0 rma on rma.iBodyId = tCore_Data_0.iBodyId\r\n\r\n                    JOIN tCore_Indta_0 ON tCore_Data_0.iBodyId = tCore_Indta_0.iBodyId\r\n                    JOIN mCore_Product ON mCore_Product.iMasterId = tCore_Indta_0.iProduct\r\n\r\n                    WHERE rma.sRmaNo = '{rmano}' and bUpdateStocks = 1 AND bSuspended = 0 AND bSuspendUpdateStocks = 0 AND tCore_Data_0.iAuthStatus < 2\r\n                       AND iProductType<> 1 AND iProductType<> 5\r\n                     AND iStatus<> 5 and fQuantityInBase< 0 ) dt group by iProduct, RmaNo\r\n  ) dt join mcore_product pr on pr.imasterid = dt.iProduct left join muCore_Product_Units uts on uts.iMasterId = pr.iMasterId   left join mCore_Units muts on muts.iMasterId = uts.iDefaultSalesUnit order by iProduct";
        }
        public static string GetRmaDataStockIn(string rmano, string stockoutdocno)
        {
            return $"select pr.iMasterId ItemId, uts.iMasterId UnitId, uts.sName UnitName,  rma.sRmaNo RmaNo from tCore_Rma_0 rma join tCore_Data_0 d on d.iBodyId = rma.iBodyId join tCore_Header_0 h on h.iHeaderId = d.iHeaderId  join tCore_Indta_0 stk on stk.iBodyId = d.iBodyId  join mCore_Product pr on pr.iMasterId = stk.iProduct left join muCore_Product_Units muts  on muts.iMasterId = pr.iMasterId left join  mCore_Units uts on uts.iMasterId = muts.iDefaultSalesUnit  where rma.sRmaNo = '{rmano}' and h.sVoucherNo = '{stockoutdocno}' and h.iVoucherType = 5379 and not exists(select sRmaNo from tCore_Rma_0 rma1 join tCore_Data_0 dd on dd.iBodyId = rma1.iBodyId join tCore_Header_0 hh on hh.iHeaderId = dd.iHeaderId  where hh.iHeaderId = 2052 and rma1.sRmaNo = '{rmano}')";
        }
        public static string GetRmaItemQry(string rmano)
        {
            return $"select p.iMasterId ItemId, p.sCode ItemCode, p.sName ItemName,u.iMasterId UnitId, u.sName UnitName,'{rmano}' RmaNo,,0 as AvailableStock,SellingRate= (select top 1 fVal0  from mCore_SellingPriceBookDetails where bMarkDeleted = 0 and iProductId =  p.iMasterId order by iStartDate desc)  from mCore_Product p left join muCore_Product_Units uts on uts.iMasterId = p.iMasterId left join mCore_Units u on u.iMasterId = uts.iDefaultSalesUnit where p.imasterid = 5 ";
        }
    }
}
